apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v3
  labels:
    app: sample-app
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
      version: v3
  template:
    metadata:
      labels:
        app: sample-app
        version: v3
    spec:
      containers:
      - name: web-server
        image: nginx:1.23
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v3.0"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: app-content-v3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-content-v3
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Sample App v3</title>
        <style>
            body { font-family: Arial; text-align: center; background-color: #fff3e0; }
            .container { margin-top: 100px; }
            .version { color: #f57c00; font-size: 24px; font-weight: bold; }
            .canary { background-color: #ffcc02; padding: 10px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Sample Application</h1>
            <p class="version">Version 3.0 - Canary Release</p>
            <div class="canary">
                <p><strong>🐤 CANARY VERSION</strong></p>
                <p>This version includes experimental features</p>
            </div>
            <ul style="text-align: left; display: inline-block;">
                <li>Advanced analytics</li>
                <li>Real-time monitoring</li>
                <li>Enhanced security</li>
                <li>Performance optimizations</li>
            </ul>
        </div>
    </body>
    </html>
