apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v2
  labels:
    app: sample-app
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
      version: v2
  template:
    metadata:
      labels:
        app: sample-app
        version: v2
    spec:
      containers:
      - name: web-server
        image: nginx:1.22
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v2.0"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: app-content-v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-content-v2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Sample App v2</title>
        <style>
            body { font-family: Arial; text-align: center; background-color: #e8f5e8; }
            .container { margin-top: 100px; }
            .version { color: #2e7d32; font-size: 24px; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Sample Application</h1>
            <p class="version">Version 2.0 - Green Environment</p>
            <p>This is the updated version with new features</p>
            <ul style="text-align: left; display: inline-block;">
                <li>Enhanced performance</li>
                <li>New user interface</li>
                <li>Bug fixes</li>
            </ul>
        </div>
    </body>
    </html>
