apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v1
  labels:
    app: sample-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-app
        version: v1
    spec:
      containers:
      - name: web-server
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1.0"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: app-content-v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-content-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Sample App v1</title>
        <style>
            body { font-family: Arial; text-align: center; background-color: #e3f2fd; }
            .container { margin-top: 100px; }
            .version { color: #1976d2; font-size: 24px; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Sample Application</h1>
            <p class="version">Version 1.0 - Blue Environment</p>
            <p>This is the initial version of our application</p>
        </div>
    </body>
    </html>
