apiVersion: v1
kind: Service
metadata:
  name: sample-app-blue
  labels:
    app: sample-app
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: sample-app
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-green
  labels:
    app: sample-app
    version: v2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  selector:
    app: sample-app
    version: v2
